# from: https://jfrog.com/help/r/jfrog-pipelines-documentation/gitrepo
template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: my_app_repo
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: helcorin/jfrog-pipeline
      branches:
        include: main

pipelines:
  - name: pipeline_1
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: my_app_repo
        execution:
          onExecute:
            # Data from input resources is available as env variables in the step
            - echo "Initial test step"